version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - '8069:8069'
    volumes:
      - 'odoo-web-data-prod:/var/lib/odoo'
      - './extra-addons:/mnt/extra-addons'  # AÃ±adido para tus addons personalizados
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD:-odoo}
    command: >
      sh -c "sleep 10 && 
             odoo -c /etc/odoo/odoo.conf 
             --db_host=db 
             --db_port=5432 
             --db_user=odoo 
             --db_password=${POSTGRES_PASSWORD:-odoo}"
    restart: always

  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=odoo
    volumes:
      - 'odoo-db-data-prod:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  odoo-web-data-prod:
  odoo-db-data-prod:
