version: '3.8'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data-prod:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD:-odoo}
    command: --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data-prod:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-web-data-prod:
  odoo-db-data-prod:
