version: '3.8'

services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8069:8069'
    volumes:
      - 'odoo-web-data-prod:/var/lib/odoo'
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD:-odoo}
    restart: always

  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=odoo
    volumes:
      - 'odoo-db-data-prod:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: always

volumes:
  odoo-web-data-prod:
  odoo-db-data-prod:
